### ISSUE TITLE
Fail to create new version of ObservedData if it has related objects

### ISSUE THREAD

**Issue by oliveriandrea** [oasis-open/cti-python-stix2#122]
If you try to generate a new version of an ObservedData which contains related objects (like domain-name -> ipv4) you obtain a fatal error
Example:
`from stix2 import ObservedData`
`from datetime import datetime`
`data = ObservedData(first_observed=datetime.now(),last_observed=datetime.now(),number_observed=1,objects={'src_ip': {'type':'ipv4-addr','value':'127.0.0.1/32'}, 'domain':{'type':'domain-name','value':'example.com','resolves_to_refs':['src_ip']}})`
`new_version = data.new_version(last_observed=datetime.now())`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/stix2/base.py", line 175, in new_version
    return _new_version(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/stix2/utils.py", line 212, in new_version
    new_obj_inner = copy.deepcopy(data._inner)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.6/site-packages/stix2/base.py", line 167, in __deepcopy__
    return cls(**new_inner)
  File "/usr/local/lib/python3.6/site-packages/stix2/base.py", line 221, in __init__
    super(_Observable, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/stix2/base.py", line 128, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/usr/local/lib/python3.6/site-packages/stix2/base.py", line 251, in _check_property
    self._check_ref(ref, prop, prop_name)
  File "/usr/local/lib/python3.6/site-packages/stix2/base.py", line 225, in _check_ref
    raise InvalidObjRefError(self.__class__, prop_name, "'%s' is not a valid object in local scope" % ref)`

The error appears also if you use an incremental value as index in objects dictionary

**Comment by gtback** [comment]
Thanks, @oliveriandrea. I was able to reproduce that error one time, but after that it worked OK, and I couldn't get it to happen again. Creating multiple objects in this way is tricky (especially when there are circular references), which is part of the reason you can explicitly pass `_valid_refs` when creating an Cyber Observable Object, so you can tell the library "I know this will be a valid object name". You may be able to get around it be explicitly creating the IP and Domain objects first using this approach, then creating the Observed Data.

Let us know if that doesn't work or you are still having problems.

**Comment by gtback** [comment]
Oh, sorry, I didn't read your message (or the error) closely enough. The initial create is going fine, the problem is that the `deepcopy` performed by the `new_version` function doesn't have enough information to preserve `_valid_refs`. That's my fault for not understanding. 😞 

@clenk, any ideas for making this work?

We made the choice in python-stix2 to make objects immutable* once created to make the logic for checking for valid content more centralized and predictable (you can't create a half-finished object and serialize it, for example). Modifying them requires the new_version function, which you're already discovered 😁 

* with some caveats/exceptions, if you really know what you're doing.

**Comment by clenk** [comment]
Sorry for taking so long to look at this. I think we could make this work if we assume that we don't need to check `_valid_refs` again when performing a `deepcopy`.
