### ISSUE TITLE
Something is awry with how filter params are being passed from the TAXII2 datastore back to taxii2client

### ISSUE THREAD

**Issue by treyka** [oasis-open/cti-python-stix2#163]
Cf. https://github.com/oasis-open/cti-taxii-client/issues/33, I do:

```
from stix2.workbench import *
from taxii2client import Collection
collection = Collection("https://obfuscated.mitre.org/taxii", verify=False)
tc_source = TAXIICollectionSource(collection)
add_data_source(tc_source)
response = indicators()
```

and get:

```
~/cti-python-stix2/venv/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/cti-python-stix2/stix2/workbench.py", line 208, in indicators
    return query(filter_list)
  File "~/cti-python-stix2/stix2/datastore/__init__.py", line 98, in query
    return self.source.query(*args, **kwargs)
  File "~/cti-python-stix2/stix2/datastore/__init__.py", line 542, in query
    data = ds.query(query=query, _composite_filters=all_filters)
  File "~/cti-python-stix2/stix2/datastore/taxii.py", line 235, in query
    all_data = self.collection.get_objects(**taxii_filters_dict)["objects"]
  File "~/cti-python-stix2/venv/lib/python3.5/site-packages/taxii2client/__init__.py", line 439, in get_objects
    self._verify_can_read()
  File "~/cti-python-stix2/venv/lib/python3.5/site-packages/taxii2client/__init__.py", line 423, in _verify_can_read
    if not self.can_read:
  File "~/cti-python-stix2/venv/lib/python3.5/site-packages/taxii2client/__init__.py", line 367, in can_read
    self._ensure_loaded()
  File "~/cti-python-stix2/venv/lib/python3.5/site-packages/taxii2client/__init__.py", line 420, in _ensure_loaded
    self.refresh()
  File "~/cti-python-stix2/venv/lib/python3.5/site-packages/taxii2client/__init__.py", line 434, in refresh
    self._populate_fields(**response)
TypeError: _populate_fields() got an unexpected keyword argument 'default'
```

Unfortunately I don't have the bandwidth to fire up my debugger and cook up a pull-request because of the looming monstrosity that is RSAC but clearly something is awry with how filter params are being passed from the TAXII2 datastore back to taxii2client.

**Comment by gtback** [comment]
`https://obfuscated.mitre.org/taxii` is a Server Discovery endpoint, which is why it contains a `default` key, which isn't expected by the `Collection`. We can likely make the error message more clear, but try passing a collection URL to the `Collection` class, or looping through the API Roots and corresponding Collections on each API Root to build `TAXIICollectionSource` objects.

**Comment by treyka** [comment]
@gtback Right, my bad. Thanks for the clarification!
