### ISSUE TITLE
allow_custom is not inherited

### ISSUE THREAD

**Issue by cugu** [oasis-open/cti-python-stix2#176]
Even when `allow_custom=True` is set on parent and child elements, included elements are not allowed to have custom fields.

Example:
```python
from datetime import datetime

import stix2

artifact = stix2.File(
    allow_custom=True,
    name='test',
    foo='bar'
)

stix2.ObservedData(
    allow_custom=True,
    first_observed=datetime.now(),
    last_observed=datetime.now(),
    number_observed=0,
    objects={"0": artifact}
)
```
results in:
```
Traceback (most recent call last):
  File "C:/.../stix.py", line 16, in <module>
    objects={"0": artifact}
  File "C:\Python36\lib\site-packages\stix2\base.py", line 158, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "C:\Python36\lib\site-packages\stix2\base.py", line 89, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "C:\Python36\lib\site-packages\stix2\v20\observables.py", line 42, in clean
    parsed_obj = parse_observable(obj, valid_refs)
  File "C:\Python36\lib\site-packages\stix2\v20\observables.py", line 959, in parse_observable
    return obj_class(allow_custom=allow_custom, **obj)
  File "C:\Python36\lib\site-packages\stix2\base.py", line 271, in __init__
    super(_Observable, self).__init__(**kwargs)
  File "C:\Python36\lib\site-packages\stix2\base.py", line 141, in __init__
    raise ExtraPropertiesError(cls, extra_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for File: (foo).
```

**Comment by m0jtaba** [comment]
Could this also be related:
``` python
def attack():
    """
    Import attack into TAXII server
    """
    collection = Collection(
        "http://127.0.0.1:5000/mitre/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/",
        user="guest",
        password="guest")
    # create TAXIICollectionSINK and push STIX content to it
    taxii_collection_sink = TAXIICollectionSink(collection)
    data = json.load(open('enterprise-attack.json'))
    taxii_collection_sink.add(data)
```

``` log
File "import_attck_to_taxii.py", line 92, in <module>
    main()
  File "import_attck_to_taxii.py", line 21, in main
    attack()
  File "import_attck_to_taxii.py", line 72, in attack
    taxii_collection_sink.add(data)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/datastore/taxii.py", line 78, in add
    bundle = parse(stix_data, allow_custom=self.allow_custom, version=version).serialize(encoding="utf-8")
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/core.py", line 101, in parse
    obj = dict_to_stix2(obj, allow_custom, version)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/core.py", line 148, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, **stix_dict)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/core.py", line 69, in __init__
    super(Bundle, self).__init__(**kwargs)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/base.py", line 158, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/base.py", line 89, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/properties.py", line 115, in clean
    valid = self.contained.clean(item)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/core.py", line 39, in clean
    parsed_obj = parse(dictified)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/core.py", line 101, in parse
    obj = dict_to_stix2(obj, allow_custom, version)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/core.py", line 148, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, **stix_dict)
  File "/home/vagrant/taxii-server/lib64/python3.6/site-packages/stix2/base.py", line 141, in __init__
    raise ExtraPropertiesError(cls, extra_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for AttackPattern: (x_mitre_data_sources, x_mitre_permissions_required, x_mitre_platforms).

**Comment by m0jtaba** [comment]
The issue with extra properties in my case can be resolve via:
``` python
taxii_collection_sink = TAXIICollectionSink(collection, allow_custom=True)
```

``` python
def attack():
    """
    Import attack into TAXII server
    """
    collection = Collection(
        "http://127.0.0.1:5000/mitre/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/",
        user="guest",
        password="guest")
    # create TAXIICollectionSINK and push STIX content to it
    taxii_collection_sink = TAXIICollectionSink(collection, allow_custom=True)
    data = json.load(open('enterprise-attack.json'))
    taxii_collection_sink.add(data)
```

**Comment by clenk** [comment]
Thanks for reporting this bug, @cugu! I'm working on a fix. The bug is that we pass `allow_custom` when adding an SDO/SRO to a bundle, but not when adding an observable to an ObservedData object.

@m0jtaba This is unrelated to what you're seeing with custom properties in TAXIICollectionSink.

**Comment by cugu** [comment]
Thanks! So adding allow_custom to the ObservedData is sufficient?

**Comment by clenk** [comment]
Yes, the example from your original post should now work with the latest master.

**Comment by criptk** [comment]
I am getting a similar issue trying to do this 
-----
from stix2 import parse

file_handle = open("2c820bcefc45d0883343fe8a4c5beabf.json")

obj = parse(file_handle)
print(type(obj))
print(obj)
-------
.
.
.

/opt/conda/lib/python3.6/site-packages/stix2/base.py in __init__(self, allow_custom, **kwargs)
    140             extra_kwargs = list(set(kwargs) - set(self._properties))
    141             if extra_kwargs:
--> 142                 raise ExtraPropertiesError(cls, extra_kwargs)
    143         if custom_props:
    144             self.__allow_custom = True

ExtraPropertiesError: Unexpected properties for AttackPattern: (x_mitre_data_sources, x_mitre_detection, x_mitre_permissions_required, x_mitre_platforms, x_mitre_version).

Then i changed to allow_custom=True and a new error came along 

/opt/conda/lib/python3.6/site-packages/stix2/v20/observables.py in values(self)
    727     def values(self):
    728         # Needed because 'values' is a property on collections.Mapping objects
--> 729         return CallableValues(self, self._inner['values'])
    730 
    731 

KeyError: 'values'

Any clues ?

**Comment by emmanvg** [comment]
@criptk, most likely your issue is that you are trying to parse a file that contains custom properties and `stix2` by default will not allow them even at the parser level. You could try:

``` python 
import stix2

file_handle = open("2c820bcefc45d0883343fe8a4c5beabf.json")

obj = parse(file_handle, allow_custom=True)
print(type(obj))
print(obj)
```

**Comment by clenk** [comment]
Hi @criptk I notice you tried `allow_custom=True` but I'm not able to reproduce your error. Since this is a different problem, can you please open a new issue and include a little more information? Does the STIX content in your JSON file contain custom properties? Does it contain a `values` property? Can you show more of the stacktrace of where `values` is being called?

Thanks!
