### ISSUE TITLE
Creating LanguageContent object has error

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-python-stix2#238]
If you pass a language content object an empty contents dictionary, you get an exception saying it must be non-empty.  I do not see anywhere in the 2.1 specification that requires this.

```
from stix2.v21 import LanguageContent, Campaign
camp = Campaign(name='foo')
LanguageContent(object_ref=camp.id, object_modified=camp.modified, contents={})
```
produces:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmg/work/cti-i18n/p/lib/python2.7/site-packages/stix2/base.py", line 161, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/Users/jmg/work/cti-i18n/p/lib/python2.7/site-packages/stix2/base.py", line 94, in _check_property
    raise InvalidValueError(self.__class__, prop_name, reason=str(exc))
stix2.exceptions.InvalidValueError: Invalid value for LanguageContent 'contents': The dictionary property must contain a non-empty dictionary
```

**Comment by jmgnc** [comment]
also, surprisingly, if you provide one "language" w/ no translations, it works fine:
```
>>> LanguageContent(object_ref=camp.id, object_modified=camp.modified, contents={ 'bogus': {}})
LanguageContent(type='language-content', spec_version='2.1', id='language-content--87a5dfb2-c720-4e93-bc08-98666be73774', created='2019-01-05T00:04:16.827Z', modified='2019-01-05T00:04:16.827Z', object_ref='campaign--ed4dc7dc-f168-45e8-a72b-3a11eb5c156d', object_modified='2019-01-04T23:59:16.778Z', contents={'bogus': {}})                                                                                          
```

**Comment by clenk** [comment]
@jmgnc Yes, you're correct. The observed-data.objects property has a non-empty requirement and I had copied some code for dictionary properties in general. We'll get this fixed; thanks for filing an issue!

**Comment by jmgnc** [comment]
Thanks for the quick resolution!  Now I can remove some work around code.
