### ISSUE TITLE
STIX v2.1 does not handle lang granular markings

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-python-stix2#251]
If you use the last example from STIX v2.1 § 5.3.1.1 (attached as test_granlang.json), and try to extract the markings for it, you get the following error:
```$python examp.py
Traceback (most recent call last):
  File "examp.py", line 5, in <module>
    print `obj.get_markings('description')`
  File "/Users/jmg/work/cti-i18n/p/lib/python2.7/site-packages/stix2/markings/__init__.py", line 53, in get_markings                                                                          
    descendants,
  File "/Users/jmg/work/cti-i18n/p/lib/python2.7/site-packages/stix2/markings/granular_markings.py", line 47, in get_markings                                                                 
    results.update([refs])
TypeError: unhashable type: 'list'
```

Attached are both examp.py and test_granlang.json both with a .txt extension.
[examp.txt](https://github.com/oasis-open/cti-python-stix2/files/2830050/examp.txt)
[test_granlang.txt](https://github.com/oasis-open/cti-python-stix2/files/2830049/test_granlang.txt)

**Comment by emmanvg** [comment]
@jmgnc thanks for catching this bug. Essentially the markings API portion was outdated and did not include support for lang markings.

With these changes, calls like `get_markings()` by default will include **BOTH** markings to lang and marking-definition identifiers. If you are only interested in one you can toggle them like so: `get_markings(marking_ref=False)` or `get_markings(lang=False)` and that will exclude marking-definition markings or lang respectively.

This should be available on the next release.

**Comment by jmgnc** [comment]
Thanks, I'll test out the code shortly.
