### ISSUE TITLE
Freetaxii get certification error

### ISSUE THREAD

**Issue by AhmedAkkarii** [oasis-open/cti-python-stix2#267]
`from stix2 import TAXIICollectionSource`
`from taxii2client import Collection`
`collection = Collection("https://test.freetaxii.com:8000/osint/collections/34f8c42d-213a-480d-9046-0bd8a8f25680/objects/",verify=False)`
`tc_source = TAXIICollectionSource(collection)`
`stix_obj = tc_source.get("indicator--50ccf36e-1e9f-4f22-ad48-b8e824a5255a")`
`print(stix_obj)`

After issuing the "verify=False" and get to escape certification validation, it seems that the problem is still exist. Here's the error output:

/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

requests.exceptions.HTTPError: 406 Client Error: Not Acceptable for url: https://test.freetaxii.com:8000/osint/collections/34f8c42d-213a-480d-9046-0bd8a8f25680/objects/

Traceback (most recent call last):
  File "test3.py", line 7, in <module>
    tc_source = TAXIICollectionSource(collection)
  File "/usr/local/lib/python3.7/dist-packages/stix2/datastore/taxii.py", line 166, in __init__
    " Collection object provided could not be reached. Recieved error:", e,
stix2.datastore.DataSourceError: The underlying TAXII Collection resource defined in the supplied TAXII Collection object provided could not be reached. Recieved error: "406 Client Error: Not Acceptable for url: https://test.freetaxii.com:8000/osint/collections/34f8c42d-213a-480d-9046-0bd8a8f25680/objects/"

**Comment by clenk** [comment]
Hi @AhmedAkkarii,

FreeTaxii only accepts TAXII 2.1 requests, but currently this library only supports TAXII 2.0. You can track progress on this front with this issue on python-stix2's `taxii2client` dependency: [https://github.com/oasis-open/cti-taxii-client/issues/41](https://github.com/oasis-open/cti-taxii-client/issues/41).
