### ISSUE TITLE
Adding SCO to the MemoryStore results in error

### ISSUE THREAD

**Issue by emmanvg** [oasis-open/cti-python-stix2#340]
Below an example of how to trigger the problem:

``` python
from stix2.v21 import observables
from stix2 import MemoryStore

mem_store = MemoryStore()

file_observable = observables.File(
    name="example.exe",
    size=68 * 1000,
    magic_number_hex="50000000",
    hashes={
        "SHA-256": "841a8921140aba50671ebb0770fecc4ee308c4952cfeff8de154ab14eeef4649"
    }
)

mem_store.add(file_observable)
```

I obtain the following traceback:

```
Traceback (most recent call last):
  File "C:/Users/user-1/example_project/mem_store.py", line 98, in <module>
    example()
  File "C:/Users/user-1/example_project/mem_store.py", line 94, in example
    mem_store.add(file_observable)
  File "C:\Users\user-1\venv\lib\site-packages\stix2\datastore\__init__.py", line 216, in add
    return self.sink.add(*args, **kwargs)
  File "C:\Users\user-1\venv\lib\site-packages\stix2\datastore\memory.py", line 185, in add
    _add(self, stix_data, self.allow_custom, version)
  File "C:\Users\user-1\venv\lib\site-packages\stix2\datastore\memory.py", line 62, in _add
    obj_family.add(stix_obj)
  File "C:\Users\user-1\venv\lib\site-packages\stix2\datastore\memory.py", line 77, in add
    self.all_versions[obj["modified"]] = obj
  File "C:\Users\user-1\venv\lib\site-packages\stix2\base.py", line 195, in __getitem__
    return self._inner[key]
KeyError: 'modified'
```

**Comment by chisholm** [comment]
Looks like the error is in version-related code which is trying to access the `modified` property.  2.1 SCO's don't have that property.  Obviously that code was written before 2.1 SCOs became TLOs.

**Comment by clenk** [comment]
Looks like we'll need to do it in the filesystem store, too.
