### ISSUE TITLE
Unable to add() Bundle. 

### ISSUE THREAD

**Issue by FearonChris** [oasis-open/cti-python-stix2#76]
example usage:

```
bundle      = Bundle(*bArgs, allow_custom=True) 
store.add(bundle)
```

```
Traceback (most recent call last):
  File "stix.py", line 166, in <module>
    store.add(bundle)
  File "/usr/local/lib/python2.7/dist-packages/stix2/environment.py", line 147, in add
    return self.sink.add(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/stix2/sources/filesystem.py", line 86, in add
    _check_path_and_write(self._stix_dir, stix_data)
  File "/usr/local/lib/python2.7/dist-packages/stix2/sources/filesystem.py", line 82, in _check_path_and_write
    f.write(str(Bundle(stix_obj)))
  File "/usr/local/lib/python2.7/dist-packages/stix2/core.py", line 62, in __init__
    super(Bundle, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/stix2/base.py", line 121, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/stix2/base.py", line 57, in _check_property
    raise InvalidValueError(self.__class__, prop_name, reason=str(exc))
stix2.exceptions.InvalidValueError: Invalid value for Bundle 'objects': This property may not contain a Bundle object
```

FYI i'm using the patched code submitted in #73

**Comment by FearonChris** [comment]
Issue isn't restricted to type Bundle. Unable to add valid stix objects with custom properties to the datastore.

**Comment by gtback** [comment]
Thanks, @FearonChris . 

We need to take a deeper look at how we use `allow_custom`, and some of the behind-the-scenes transformations to/from dicts/objects in order to best address this.

**Comment by gtback** [comment]
There are two separate issues. One involves adding any Bundle to the FileSystem and TAXII data sinks (and is a pretty easy fix). The other relates to how both of these create Bundles by default; this is what we are working to figure out.
